# Generated by Django 2.2.3 on 2019-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('asignatura', models.CharField(default='', max_length=255)),
                ('comentarios', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(default='', max_length=255)),
                ('periodo', models.CharField(default='', max_length=255)),
                ('asignatura', models.CharField(default='', max_length=255)),
                ('matriculados', models.IntegerField(default=0)),
                ('evaluaron', models.IntegerField(default=0)),
                ('p9', models.CharField(default='', max_length=255)),
                ('p10', models.CharField(default='', max_length=255)),
                ('p11', models.CharField(default='', max_length=255)),
                ('p12', models.CharField(default='', max_length=255)),
                ('p13', models.CharField(default='', max_length=255)),
                ('p14', models.CharField(default='', max_length=255)),
                ('p15', models.CharField(default='', max_length=255)),
                ('p16', models.CharField(default='', max_length=255)),
                ('p17', models.CharField(default='', max_length=255)),
                ('p18', models.CharField(default='', max_length=255)),
                ('p19', models.CharField(default='', max_length=255)),
                ('p20', models.CharField(default='', max_length=255)),
                ('promedio', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'evaluaciones',
            },
        ),
    ]
